### ISSUE TITLE
In Windows CMD.EXE, Joker REPL Resets Screen Color

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#104]
My `cmd.exe` brings up black-on-white (white-background) windows, and running Joker in REPL mode causes everything after the prompt to be black, until typing onto it.

I suspect [readline](https://github.com/chzyer/readline) is the culprit here, but haven't tested that independently of Joker yet.

**Comment by jcburley** [comment]
Note that the issue is not visible for:

```
D:\Users\craig\.go\bin>.\joker.exe -e "(loop [input-string (read-line)] (println input-string) (recur (read-line)))"
```

**Comment by candid82** [comment]
I am pretty sure this is a readline issue. Do you mind reporting it in readline project?

**Comment by jcburley** [comment]
Okay, here it is:

https://github.com/chzyer/readline/issues/159

**Comment by candid82** [comment]
[This](https://github.com/candid82/joker/commit/58fffb5589b38aefc83c46b3dbb150616a3d0e32) commit allows to turn off joker's readline functionality by passing `--no-readline` flag. Of course this is not a real solution since repl is hard to use without readline and there is no rlwrap for Windows as far as I know (but it may work in cygwin).

**Comment by candid82** [comment]
Closing since this can only be fixed upstream.
