### ISSUE TITLE
Support Java and/or JavaScript

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#106]
Here's a totally wacky idea: Implement (directly in `.joke` code, or perhaps -- if small enough -- in Joker itself, via Go or C code) interpreters for Java and/or JavaScript.

The idea here would be to support all those wonderful libraries without adding the overhead of compilers, JIT, etc. I.e. "pure" interpretation.

There might be existing code we can leverage to add to Joker itself. But that might increase the startup time and/or executable size.

So, another approach would be to implement such interpreters as `.joke` libraries that can be pulled in on-demand, so Joker scripts not needing them would avoid any overhead.

(I realize this might seem far-fetched, but it's not quite as crazy as asking for a DWIM feature....)

**Comment by jcburley** [comment]
Not sure what to make of this:

https://golang.org/pkg/syscall/js/

But it looks interesting! Is it possible Joker could leverage it (usefully)? I haven't played around with it much yet....

**Comment by candid82** [comment]
This seems completely insurmountable to me. Besides, implementing Java(Script) interpreter(s) won't be very useful since their usefulness comes from the corresponding platforms (standard library, runtime, tooling etc) and not from language syntax.

`syscall/js` is for Go's WebAssembly backend as I understand.

Closing for now. Feel free to experiment in this area if you think it's worth it.
