### ISSUE TITLE
Flimsy cursor visibility (Win64 10.0)

### ISSUE THREAD

**Issue by deliciousowl** [candid82/joker#112]
Occasionally the cursor will disappear. (Or turn the same color as the bg color?)

This can be either for a longer blink than usual, or it will be "off" altogether until you continue to interact with the keyboard again. However, sometimes it stays "off" despite that.

This is more often the case when you press ↑ (upward arrow) on the keyboard to bring up the previous line that you executed. It has also occurred when using ← (leftward arrow), to edit the current line.

I don't think I've seen it happen when typing normally or executing commands.

**Comment by candid82** [comment]
This is most likely a [readline](https://github.com/chzyer/readline) issue. Joker now has the ability (not released yet) to turn off readline functionality by providing `--no-readline` flag. Obviously this is not a real solution since repl is barely usable without readline functionality. The idea behind `--no-readline` is to allow people to use `rlwrap` instead of Joker's builtin readline, but I don't think `rlwrap` is available on Windows.

**Comment by candid82** [comment]
Closing since this can only be fixed upstream.
