### ISSUE TITLE
Lint problem with shadow-cljs conditional reading

### ISSUE THREAD

**Issue by khmelevskii** [candid82/joker#195]
I use shadow-cljs conditional reading https://shadow-cljs.github.io/docs/UsersGuide.html#_conditional_reading
and joker can't lint the following code
```
(ns app.test
  (:require
   [clojure.core]
   #?@(:app [[stubs.spec :as spec]]
       :dev [[app.spec :as spec]])))

(defn my-fn[] nil)

#?(:dev
   (my-fn
    [:props ::spec/props]
    ::spec/inner-props))
```
=> Read error: Unexpected end of file

but if I insert, for example, `(comment)` to the end of file everything works fine.

**Comment by candid82** [comment]
`Unexpected end of file` is fixed by https://github.com/candid82/joker/commit/8b8d5e83b79b3cb269af6a3c60da34881df8295a. The linter will still warn on `::spec/...` keywords as neither `:app` nor `:dev` features are activated when linting cljs files (and there is no way for the linter to know which one should be active).

**Comment by khmelevskii** [comment]
Thank you
