### ISSUE TITLE
Lint multiple files at once

### ISSUE THREAD

**Issue by SevereOverfl0w** [candid82/joker#199]
`joker --lint **/*.clj` doesn't work for multiple files, giving:

```
Error: Cannot provide arguments to code while linting it.
```

**Comment by khmelevskii** [comment]
+1

**Comment by harold** [comment]
I have used `find . | grep clj | xargs -t -n 1 joker --lint` and experienced joy.

**Comment by candid82** [comment]
Linting multiple files is more complicated than it seems because reading / parsing / linting changes internal state that would have to be reset before linting every file. The simplest and cleanest way to do this is to invoke Joker separately for each file, which can be achieved with a one-liner like the one @harold suggested or more elaborate scripts. Considering it's pretty easy to achieve outside of Joker, I don't think Joker will support linting multiple files per invocation any time soon.
