### ISSUE TITLE
`<file>:0:0:` on bad `condp`

### ISSUE THREAD

**Issue by harold** [candid82/joker#216]
Man, joker is great! Never would have found some silly code of ours without it.

```
harold@wintermute:~ []$ cat test.clj 
(ns test)

(condp = "foo" "bar")
harold@wintermute:~ []$ joker --lint ./test.clj
<file>:0:0: Parse warning: unused binding: pred__1
<file>:0:0: Parse warning: unused binding: expr__2
```

We actually had some code that was structurally equivalent to this simplified example. That is, a `condp` with really only a default case. Comically, this has been in production and working for months.

With joker's help I was able to track it down, but it would be cool if the line/column numbers were correct (and not just zeros).

Thanks as ever.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/e1e5dcff6dcc4c4c445e4124380989f1d7422751. Note that I've added more readable error messages with correct line/column numbers, but cryptic `pred__1` and `expr__2` messages will still be generated. I could fix line/column numbers for those as well, but that would result in duplicate error messages in editors (currently those cryptic message don't show up in editors due to wrong line/column numbers). It'd be tricky to suppress those messages completely and I feel like it's not worth the effort.
