### ISSUE TITLE
Nix version is pretty old it seems

### ISSUE THREAD

**Issue by didibus** [candid82/joker#230]
I just installed Joker using Nix, and it installed v0.8.7. The binaries from the download page are at v0.12.

Maybe if Nix install route is not being updated, it would be best to remove it from the readme?

**Comment by candid82** [comment]
I think it makes sense to remove it unless @andrestylianos is still interested in maintaining Joker build for Nix.

**Comment by andrestylianos** [comment]
Thanks for pinging me! I still use joker, but the version I'm on is serving me quite well for linting so I got lazy in updating it.

I'll update it soon and try to better keep it updated with new releases! It's not much work and I don't mind contributing with this since I've benefited a lot from it.

**Comment by andrestylianos** [comment]
Just checked it out and it seems like contributors other than me have been keeping it up to date, so the current version in Nix should be v0.12.2 as of https://github.com/NixOS/nixpkgs/pull/59737.

@didibus, could you check if you need to update your nix channel? I'll update the joker package to 0.12.4 tomorrow anyway.

**Comment by candid82** [comment]
Thanks @andrestylianos!

**Comment by didibus** [comment]
@andrestylianos Oh yup, looked like I had an old one. Now upgrading broke my Nix :stuck_out_tongue: I'll have to debug that.

**Comment by andrestylianos** [comment]
No prob!

PR for version bump from 0.12.2 to 0.12.4 is up: https://github.com/NixOS/nixpkgs/pull/63013. They're usually pretty quick about merging simple PRs like this so it should be merged in a few days, and take a couple more to be on the unstable channel.

Since there's nothing else to do here, we can probably close this issue?
