### ISSUE TITLE
Suggestion: pass streams between processes

### ISSUE THREAD

**Issue by hlship** [candid82/joker#236]
I've been writing some scripts that bind together some existing command line tools (such as `jq` and `gron`).

I'd love to see a way that I can pipe the output of `jq` directly into `gron`.

Using what's currently available in `joker.os`, I have to capture the entire output of `jq` as a string, before passing that to `gron`.

Ideally, I might add further filter to my chain, if there was a streaming option.

**Comment by pmonks** [comment]
Raynes' ["conch" Clojure library](https://github.com/Raynes/conch#piping) supports this, and I believe it's fairly widely used.  A joker implementation of the conch API might be nice?

**Comment by candid82** [comment]
@hlship I've added `joker.io/pipe` and `joker.io/close` functions, and now all pieces are in place to do "streaming" between processes in Joker:

```Clojure
;; equivalent of "echo 'hello pipe!' | cat"
(let [[reader writer] (joker.io/pipe)
      cat-ch (go (joker.os/exec "cat" {:stdin reader :stdout *out*}))
      echo-ch (go
               (joker.os/exec "echo" {:args ["hello pipe!"] :stdout writer})
               ;; must close writer or cat will never exit
               (joker.io/close writer))]
  (<! cat-ch)
  (<! echo-ch))
```
While it's certainly cool that the above is now possible in Joker, I don't think it's very interesting from practical point of view as the same can be more easily and efficiently achieved by using bash pipes:
```
(joker.os/exec "bash" {:args ["-c" "echo 'hello pipe!' | cat"] :stdout *out*})
```

Currently Joker doesn't allow you to do much with "streams" (IOReader, IOWriter, File), other than connecting them with files, processes and now with each other (by means of `joker.io/pipe`). 

Please let me know if there is any particular use case that you'd like to address in Joker land rather than with bash pipes.

**Comment by candid82** [comment]
@pmonks conch's API seems to high level and opinionated to me to be built into Joker, but it could probably be implemented as a separate library.

**Comment by hlship** [comment]
Well, I like the idea that I can assemble commands in Joker code, and not have to worry about things like dealing with argument quoting (my use case is passing complex `jq` expressions around, which would be ugly/painful to properly quote, just so that bash can unquote them).    I'll see about updating my scripts on the next Joker release to see if it's actually an improvement (readability and/or performance).  Thanks!

**Comment by crocket** [comment]
Does joker support libraries? As far as I know, it only supports loading individual joker files.

**Comment by jcburley** [comment]
It has some support for libraries.

See: https://github.com/candid82/joker/blob/master/LIBRARIES.md
