### ISSUE TITLE
joker doesn't recognize `use` + `:as`

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#28]
Example:

```
(ns dre.integration.frontend.core
  (:use [etaoin.api :as eta :exclude [chrome]])
  (:require [etaoin.keys :as k]))

(def chrome (eta/chrome)) ;; Unable to resolve symbol eta/chrome
```

**Comment by candid82** [comment]
`use` doesn't allow proper symbol resolution since any symbol becomes potentially legit as it may come from the used namespace. This is one of few cases where Joker errors on the side of false positives and therefore essentially discourages the use of `use`. 
That said, in your particular case, if you refer to vars in `etaoin.api` via `eta/...` and not directly, why are you using `use` in the first place? Could you do `(:require [etaoin.api :as eta])` instead?

**Comment by borkdude** [comment]
Yup, I've switched to only `require` now.

**Comment by agzam** [comment]
@candid82 but can you make exception based on filename? It's probably safe to assume that `boot.core` functions and macros' can be ignored in `build.boot` file. Things like `set-env!`, `task-options!`, `deftask`, `with-pre-wrap`, `with-pass-thru`, `by-name`, `by-ext`, `boot.util` functions, etc.

**Comment by candid82** [comment]
I guess for *.boot files Joker could inject boot's vars into core namespace before linting. I'll explore this more.
