### ISSUE TITLE
Shave milliseconds off startup time.

### ISSUE THREAD

**Issue by crocket** [candid82/joker#320]
Currently, launching a minimal joker script takes 30~40 milliseconds. While this is ok for a self-contained script, requiring other scripts or calling it from a loop is going to slow joker down.

Launching babashka takes 2 milliseconds after loading the binary onto cache.

I have a few naive ideas on shaving startup time.

* Separate non-essential namespaces into modules
* Compile modules into joker bytecode.
* ...

**Comment by jcburley** [comment]
I agree this is a concern! So I've worked on it over the past few months. Please try out this branch on my Joker fork:

https://github.com/jcburley/joker/tree/gen-code

It's still a little slower than babashka (`bb`) on my MacBook Pro running Darwin, e.g 15ms versus 11ms, with arguments `-e (+ 1 1)`. I hope to shave another ms or two off the startup time by doing the sort of thing you're suggesting -- moving runtime initialization for specific namespaces into lazily-run functions. I'm not sure it'll have that much effect, though.

Beyond that, I'd have to study the generated code to find other places to optimize; however, at **2.5x** the startup time for a very simple echo-like program written in Go (that supports either `-e "just print this string"` or echoing standard input), I'm not sure -- given the state of the art of Go -- how much further we can go here.

Note that a number of the Joker namespaces (the so-called `std` namespaces) are already "lazily" initialized. But that just refers to things like the populating of the mappings (the "interning"), attaching metadata, and such; the Go language and implementation, as far as I know, does not support lazily initializing packages (upon which Joker namespaces typically depend to do their work).

(You can use the `--verbose` option to observe namespaces being lazily initialized, by the way.)

**Comment by crocket** [comment]
Do you expect to integrate your improvements into joker soon?

**Comment by jcburley** [comment]
> Do you expect to integrate your improvements into joker soon? Or, is it something that may or may not happen in years?

Can't commit to anything, but I hope to submit a clean PR by the end of next week, before going on vacation. (Will have my laptop so I can check on comments, bugs, etc., and maybe address them.)

I might integrate the changes into my `gostd` branch (on my fork), which adds Joker interfaces to many Go standard-library functions, receivers, methods, variables, and constants, to drive down it's startup-time costs.

But getting it accepted into the official version of Joker could be a challenge, because it does change the existing codebase somewhat and adds new code that would need to be maintained. My most-recent refactoring (I'm on maybe my 3rd or 4th version of this speedup project?!) improves things quite a bit, in that area as well as in performance, over the previous version; but that might not be enough.

One of the big strengths (IMO, and I think in @candid82's view/intents as author as well) is the relative ease of understanding, maintaining, and extending Joker internals. Being written in Go is a major aspect of this.

There are already several internal code generators involved in the build process for Joker, so I hope this optimization project will not be viewed as too complicated to be worth the speedup.

But, unless I come to believe something like **babashka** is a preferable platform, I plan to stick with Joker, use my fork, and maintain that -- as a fast and full-featured variant of Joker, for those who (like myself) need that sort of thing. I'm already using it in production, and have big plans for it as it comes to better meet my requirements!

(I've been dreaming about having something like Joker for over 10 years, and started some experimental work on such a thing back in 2011. I found Joker just in time to avoid trying my hand writing a Clojure clone in Go myself, saving tons of time and effort!)

> Getting close to Go native startup time should be good enough.

Offhand I don't expect my current approach being better than **3x** slower than Go-native startup time.

I'd also like to see Go offer improved startup times, by default and/or via config options. For example, I don't know how long it takes to start up various threads, but if it could avoid starting any until they're actually needed, that could be a big one. Ditto the garbage collector and any other "big" mechanism that small, quick-running scripts would rarely, if ever, need.

**Comment by jcburley** [comment]
The latest version implements the last optimization currently on my list. Looks as though it shaves maybe **2ms** off the startup time on my MacBook Pro laptop (was **17ms**, now **15ms**); the difference seems to be in the noise on my Ryzen 3 (still pretty consistently **5ms**, though I did see one invocation that hit **4ms**).

There are more cleanup, investigations, and performance assessments to do, but now I'm much more confident I can submit a fairly clean PR on this by the end of next week. Not that there won't still be a fair amount of ugly code in the main new module (**gen_code.go**), however....

**Comment by crocket** [comment]
Good to know.

**Comment by jcburley** [comment]
@candid82 -- my `gen-code` branch is "feature complete", in that the planned optimizations have been implemented and it passes the test suite on my Ubuntu (amd64 Ryzen 3) and OS X (amd64 laptop) machines.

If you haven't yet looked it over, or even if you have, I've added some info to its `DEVELOPER.md` file, as shown below.

The fast-startup version necessitated (as of this writing) these changes:

* `Regex` is now `*Regex` (a reference type), mainly so runtime initialization (from a `regexp.MustCompile()` call) can be assigned into the `.Value` or equivalent member of a static structure.
* `internalNamespaceInfo` is a new struct type that wraps `[]byte` for the core namespace, adding `init func()` (the slow version uses this for lazy-loading of core namespaces; might be replaceable via the `.Lazy` mechanism if we always map all core namespaces) and `available bool` (which aids detecting missing `a_*.go` files more elegantly).
* Many (larger/complicated) static vars' definitions and initializations have been separated out into `_init.go` files (e.g. `procs_init.go`, `environment_init.go`, etc.), which are `// +build !fast_init`, in that they aren't built into the fast-startup version of Joker.
* `Proc` now wraps the former `Proc` (renamed `ProcFn`) and adds self-identifying info (the name of the procedure and its package), to help code generation when it encounters them.
* Thunks are (unfortunately) necessary for `ProcFn`’s that, directly or indirectly (but statically), reference static variables such as `GLOBAL_ENV`, else the Go compiler refuses to compile the fast code due to cycles (!!).
* A new `core/gen_code/gen_code.go` program parallels (and is run after the running of) `gen_data.go`. It generates `a_*code.go` files that mostly define static variables representing the structures resulting when loading `joker.core` and the like; these are `// +build fast_init`, so they are compiled only when building the fast-startup version of Joker.
* `gen_data.go` changes include:
    - The list of files (`FileInfo`) has been moved into `procs.go` (might not be the best place, maybe `common.go` or a new file?) as `CoreSourceFiles` so `gen_code.go` can share it.
    - `// +build !fast_init` is emitted in pertinent files (mainly the `a_*_data.go` files, but not `a_data.go` itself).
    - Support for a `--verbose` option.
* The new `run.sh` defaults to running `gen_code.go`, which takes about only a few seconds on my Ryzen 3, and which generates these static-initializing files, built only when `-tags fast_init` is specified.
* `run.sh` continues on to building both the “normal” (slower) Joker, renamed to `joker.slow`, and the fast-startup version, hardlinked to `joker.fast`, which thus becomes the default for subsequent use (such as running `std/generate-std.joke` and then running the executable itself with whatever arguments were provided to `run.sh`).
* A new `core/code.go` module is (now) mainly a helper for `gen_code.go`, since the latter isn’t part of `package core`.
* A rudimentary tracing facility is enabled via `--trace`, mainly useful for my debugging this work, but not particularly elegant as-is; it is accompanied by a `--max-depth N` option.
* `*verbosity-level*` and related stuff was introduced, also for debugging.
* Beyond verbosity level 1 (sometimes 2), various things are “spewed” (via go-spew) at appropriate times. (Of course, this works only if Joker was built with `-tags go_spew`.)
* The new private function `joker.core/ns-init?` tells whether a namespace has been initialized (fully, including potentially lazily, loaded), useful as a debugging tool.

**Comment by jcburley** [comment]
@candid82 -- if you think it's reasonable to incorporate these changes (presumably with modifications you and others suggest), that'd be great; we'd just need to decide how best to include them.

While I work on cleaning up the code in the new `core/code.go` and `core/gen_code/gen_code.go` files, so they're more maintainable, we might want to start PR'ing individual aspects of the above list into official Joker, to keep PRs smaller and more self-contained.

If that sounds reasonable, let me know which one(s) you'd like to see first.

Or, if you prefer, the entire changeset could (when I've finished polishing the new code) be made into a single large PR.

Finally, if you don't think this should go into Joker in the near future, that's fine -- I'll probably merge it into the `gostd` version of Joker in that case, though maybe not right away. (There are some common changes, I think.) It'd be great if the `gostd` version, which brings in the entire Go standard library and, someday, optional additional 3rd-party libraries as might be chosen when building Joker, offered faster startup than it does now.

Thanks for considering this!

**Comment by candid82** [comment]
@jcburley Thank you for putting this together. I'll review and let you know my thoughts next week (hopefully).

**Comment by candid82** [comment]
@jcburley I have briefly reviewed `gen-code` branch. First of all, you've done an amazing job! I would not have thought of this approach to optimizing startup time. Even if I have, I would probably not have tried to implement it as I would have assumed it would be too difficult. But you've done it and it seems to be working very well! It does add complexity, but the result is worth it IMO. Also, if we incorporate this code into Joker we should be able to eventually get rid of pack/unpack machinery, which will balance the complexity out to some degree. 

As for how to deliver this, I would greatly prefer a series of small PRs as opposed to one giant PR. It may take some additional work on your side extracting "PR-able" chunks out of `gen-code` branch, but the review process will go much faster and smoother if PRs are relatively small and easy to understand. It probably makes sense to deliver (most of) `gen_code.go` in a single PR, but looks like there is a lot of preparation work that can be delivered piecemeal. 

Thank you for working on this! I really appreciate your interest in Joker and all your great contributions!

**Comment by jcburley** [comment]
Thanks, I really appreciate this feedback!

I'll work on PR'ing smaller chunks when I return from vacation in a few days.

**Comment by jcburley** [comment]
The (potentially) final PR on this is here:

https://github.com/candid82/joker/pull/358

**Comment by jcburley** [comment]
This is now Fixed, insofar as I'm unaware of any further improvements achievable by changing Joker itself.

**Comment by crocket** [comment]
Thanks for your efforts.
