### ISSUE TITLE
Support tab completion.

### ISSUE THREAD

**Issue by crocket** [candid82/joker#325]
It would really help with REPL browsing.

You can implement your own tab completion or use readline which adds various key bindings.
The first tab should partially complete an input. The second tab should show completions.

**Comment by jcburley** [comment]
This would be so awesome! I think much of the key support is already in `readline` (which is problematic due to lack of active maintenance, though there are better forks available that could be considered?).

**Comment by candid82** [comment]
Support for basic tab completion along with automatic parens matching just landed in master.

**Comment by jcburley** [comment]
I've been following this work somewhat and trying it out. Couple of observations:

- `.joker-history` is put in `/tmp` (or whatever), but usually such files are put in `~` (`$HOME`) so multiple users don't conflict with each other.

- This seems to fix the "exit-immediately" bug running Joker (without `--no-readline`) under the GNU Bash shell on Windows, but the prompts (such as `user=>`) don't appear. Haven't investigated this further.

Otherwise, it's really cool to have tab completion in Joker!!

**Comment by candid82** [comment]
Thanks for the feedback! I [changed](https://github.com/candid82/joker/commit/e68e0771001707912039af95f3b48c92556ee398) the location of REPL's history to `~/.jokerd/.repl_history`. 

I don't have access to Windows to test the issue with the prompt. I'll try to run a VM or something I guess....

**Comment by crocket** [comment]
Can I turn off REPL history logging?

**Comment by candid82** [comment]
—no-readline gives you bare bones experience. Why would you want to turn off history?

-Roman

**Comment by crocket** [comment]
In some environments, you want to use REPL without writing to microSD card. MicroSD card cannot take many writes. You want to minimize writes on microSD cards.

**Comment by jcburley** [comment]
> Thanks for the feedback! I [changed](https://github.com/candid82/joker/commit/e68e0771001707912039af95f3b48c92556ee398) the location of REPL's history to `~/.jokerd/.repl_history`.

Great, thanks!

> I don't have access to Windows to test the issue with the prompt. I'll try to run a VM or something I guess....

Since both `readline` and `liner` had issues with the GNU Bash environment on Windows (but not running directly from `cmd.exe` in Windows), I suspect these are issues with GNU Bash (which I think is MingCW-32 or some such thing underneath) moreso than any of the Go code running on top of them.

The only reason I use GNU Bash on Windows (to run Joker) is because that's how I do my Joker development on Windows. Not sure it's an important environment to support!

**Comment by candid82** [comment]
> In some environments, you want to use REPL without writing to microSD card. MicroSD card cannot take many writes. You want to minimize writes on microSD cards. Think about using joker on Raspberry Pi.
> 
> In-memory history doesn't write. Persistent history does.

I suggest using `rlwrap` for such special cases: `rlwrap -s -1 joker --no-readline`.

**Comment by candid82** [comment]
@crocket I added `-no-repl-history` option: https://github.com/candid82/joker/commit/e84b1d83356aee8cf3664075e474dd980486f44b

**Comment by crocket** [comment]
Great.
