### ISSUE TITLE
Support -main/entry point

### ISSUE THREAD

**Issue by dxlr8r** [candid82/joker#356]
Today you have to execute `(-main)` (or another function) to start you script. This however leads to issues when doing unit testing etc. This can be worked around today with `*main-file*`, `*file*` but we should support doing this the standard Clojure™ way.

**Comment by jcburley** [comment]
This doesn't work in Clojure (at least not with the `clojure` script on my MacBook), though; given `foo.clj` contains:

``` Clojure
(defn -main [] (println "hello world"))
```

Invoking it does not call `-main`:

```
$ clojure foo.clj
$
```

Can you give an example or two of how it would work?

**Comment by jcburley** [comment]
Maybe looking to Clojure "proper" is problematic due to the need for wrappers around Java and such?

Just throwing this out then: add a `--main` (aka `-m`) _Namespace_ option to Joker, the default being `user`.

Then, upon encountering EOF in `*main-file*`, if Joker found a `-main` function in _Namespace_, it'd invoke it with the original command-line arguments for the script (not the current value of `*command-line-args*`, as that might have changed; nor just Joker-ized `os.Args`, as that'd include non-script arguments such as the name of the script, options like `--main`, etc.).

E.g. something like this, if `myscript.joke` contains:

```
(defn -main [& args] (println "Hello world"))
```

Then this should work"

```
$ joker myscript.joke
Hello world
$
```

It wouldn't if the script began with, say, `(ns myscript)`, _unless_ `joker --main myscript` was used to run the script.

Is that (at least roughly) what you're looking for?

**Comment by candid82** [comment]
I find this additional complexity unnecessary. `(when (= *main-file* *file*) (main))` idiom is a one liner that you can add to any file and execute arbitrary code (rather than "magic" `-main` function). Similar idiom in python (`if __name__ == '__main__':`) has stood the test of time.

**Comment by jcburley** [comment]
Those of us long-accustomed to (usually compiled) languages like C, C++, etc., are used to seeing `main()` definitions that are magically invoked.

But for people relatively new to programming, and who start with scripting languages, that one-liner is _so_ much clearer as to what it's doing -- in fact, it's not a bad intro to Joker:

```
(defn main [] (println "Hello, world!"))

(when (= *main-file* *file*) (main))
```

This introduces the reader to basic concepts like defining a function (that takes no arguments), printing a line of text, comparing two strings (bound to dynamic variables), taking action when the comparison proves true, and invoking a function.

Besides introducing those most fundamental and common aspects of programming, it is expandable to define a namespace that can be referenced by a unit-testing module.

**Comment by candid82** [comment]
I consider `(when (= *main-file* *file*) (main))` construct a relatively advanced subject that is rarely needed. I, for one, have not had to use it yet simply because I tend not to write tests for the kind of scripts I use Joker for. Of course, other peoples' use cases may very well warrant more elaborate code layouts with tests etc, and that's why `*main-file*` was added to Joker.

There are two common ways of handling entry points:
1. There is one well defined function (e.g. `main()`) that is called when the program is launched. Most compiled languages (C/C++, Go etc) use this model.
2. The program is just a sequence of statements (or s-expressions) that get executed one by one when the program is launched. This model is used by most "scripting" languages (Python, Ruby, Joker etc).

Both ways are pretty straightforward. Mixing them, however, leads to complications and confusion. @jcburley even your description of how it *could* work is far from being a simple one sentence descriptions provided for the common models above. In general this mixed model is weird: Joker still has to execute all s-expressions in the file, but then, in addition to that, it *may* run a specially named function, if it exists. 

So I am leaning towards closing this issue unless I hear more compelling arguments for this feature.

**Comment by candid82** [comment]
I just realized that Clojure does implement this weird model (if you AOT with `(gen-class)`):

```Clojure
(ns example.hello
    (:gen-class))

(println "hello")

(defn -main
  []
  (println "world"))
```

Will actually output 
```
hello
world
```
if compiled and run with `java` command. 

I still think this is not a good fit for Joker.

**Comment by jcburley** [comment]
> I still think this is not a good fit for Joker.

I agree! For a scripting language, "magic" execution of a `-main` function (if it exists), while fairly trivial to implement, strikes me as unnecessarily spooky and unexpected.

(Maybe if Joker ever gets a compiler, it'd be reasonable to implement this Clojure-like behavior?)

**Comment by candid82** [comment]
> Maybe if Joker ever gets a compiler...

Speaking of which... I'd be interested in hearing your thoughts on this. An "easy" path of compiling to Go doesn't seem very interesting to me. Ideally Joker would JIT compile the code, so that it would be completely transparent for the users (just faster). However, I suspect JIT compilation inside a Go program, while possible, is challenging when crossing the boundaries between the Go code and the generated code due to GC. Rewriting everything in C/C++ is an option, but at that point it's basically a new project, and a very large one...

**Comment by dxlr8r** [comment]
My 2 cents, if there is ever an option for a compiler, one should be able to reuse the same code. So in that case, one shouldn't keep two versions of the file, one using the `-main` function as the entry-point and the other using `(when (= *main-file* *file*) (main))`?

**Comment by jcburley** [comment]
> > Maybe if Joker ever gets a compiler...
> 
> Speaking of which... I'd be interested in hearing your thoughts on this. An "easy" path of compiling to Go doesn't seem very interesting to me. Ideally Joker would JIT compile the code, so that it would be completely transparent for the users (just faster). However, I suspect JIT compilation inside a Go program, while possible, is challenging when crossing the boundaries between the Go code and the generated code due to GC. Rewriting everything in C/C++ is an option, but at that point it's basically a new project, and a very large one...

I haven't investigated this yet, so I don't know to what extent we'd have to break new ground to provide some kind of JIT in a Go environment.

My impression of Go is that it wasn't designed for that sort of thing -- more for the traditional model of compiling everything up front, into a single lean static executable, that runs without the overhead of a JIT in terms of executable size (or additional deployed artifacts), memory usage, additional threads, etc.

Given how little I know about the various technologies, I'd first want to understand what a Joker compiler would offer, over standard Clojure+JVM (especially in light of engines such as GraalVM), that'd justify such an effort?

I.e. if someone wants to compile Clojure code down to a static executable, or get JIT-type speed out of a long-running Joker script, why wouldn't they just use Clojure?

(There might well be -- now, or perhaps down the road if something like my `gostd` fork comes to full fruition -- answers in terms of functionality, e.g. access to Go libraries that are superior to equivalent JVM artifacts, if any. I don't know enough about the respective ecosystems, though obviously Java is much older and has widespread use when compared to Go.)

Before discovering Joker, I'd discovered ClojureC, a straightforward Clojure-to-C compiler, based on an old version of Clojure. Got it working, submitted a PR or two, talked with the developer, etc. As he suggested a lighterweight, faster-starting Clojure could be had via ClojureScript on (say) v8, and I really wanted a scripting engine, rather than a compiler (especially not a static one, but also not a heavyweight JIT), I looked into that and found it wanting, which led me to look into writing an interpreter, picking a promising language (Go), and then finding Joker.

Some of what I'd like to use Joker for would be great if compiled down to a static executable, just like a C or Go program can be. But it's not a short-term need (like the fast-starting, full-featured Joker is becoming), and I suspect it'd be easier to just use Clojure for those use cases unless and until clear inadequacies show themselves and point the way to how best to address them.

So while I'm (as usual) enthusiastic about the prospects of having, especially writing, a compiler, I'd like to better understand what it'd offer that isn't already out there in terms of Clojure, ClojureScript, Babashka, etc.

And would Go really be the best language for a new Clojure compiler, static or JIT? I'm curious about Rust, in light of this:

https://burleyarch.com/2020/02/08/why-discord-is-switching-from-go-to-rust/

All that being said, frankly, I think about what a Clojure-to-Go static compiler, possibly even a JIT (even if just to support better dynamic evaluation of arbitrary expressions, i.e. a solid static+JIT contender), might look like, quite often. It certainly would seem like an enjoyable thing to work on -- but moreso if it had potential widespread utility.

**Comment by jcburley** [comment]
> My 2 cents, if there is ever an option for a compiler, one should be able to reuse the same code. So in that case, one shouldn't keep two versions of the file, one using the `-main` function as the entry-point and the other using `(when (= *main-file* *file*) (main))`?

Apparently that's how things work in the Clojure world though. Not saying that's ideal, but a compiled program is tangibly different than an interpreted script when it comes to such things: the compiled program needs to know where to start, while the interpreted script just executes things as it encounters them.

This dichotomy is why I was initially more open to offering the "execute a `-main` if found" feature. But, as we've discussed, that feature would seem rather strange in a scripting language (I wonder whether any other scripting language supports such a notion?).

On the other side, the `(= *main-file* *file*)` idiom would not make much sense in a compiled program. When run, what would `*file*` and `*main-file*` even be set to, if defined at all? One could kludge up recognizing the idiom (and its equivalents) in the compiler to produce the same effect, but that makes for a strange kludge on the compiler side.

I think it's best, and most straightforward, to keep the interpreter and compiler semantics distinct: just read the code (the script) and interpret it as it's read on the one hand, and compile all the definitions and emitting a call to `-main` in the generated executable on the other. Non-definitions, such as `(println "hello")` in the example given above, would probably best be compiled sequentially into a sort of `func init()` in the Go sense, so they'd get run first, then `-main` -- at least, that seems to be how Clojure works (in effect), based on Roman's earlier comment in this thread?

So a "main" program (i.e. top-level script) that is designed to be unit-tested, run as a script, _or_ compiled into an executable, might use a reader conditional, or maybe just test whether `*main-file*` is bound like this:

```
(bound? (var *main-file*))
```

This currently returns `true` when Joker is running code from a file named on the command line, `false` when running in a REPL, evaluating an expression given on the command line, or reading forms from `stdin`.

So the "idiom" might be a little more complicated for such a flexible main script:

```
(when (and (bound? (var *main-file*)) (= *main-file* *file*)) (-main))
```

It's still a one-liner, but at this point it might make sense to define a `joker.core` function to do it.

Also, it might be worth looking into how other scripting languages (such as Python), that also have decent compilers for them, handle this (while recognizing that Lisps, in particular, are unique beasts, so they should probably be "favored" over non-Lisps like Python and Ruby when researching and deciding on such matters for Joker).

**Comment by jcburley** [comment]
Hey, I just realized something about my discussion regarding compiler technology.

It's my understanding the Go compiles down to machine code.

I.e. I'm not aware of any pCode a la the JVM, or anything else that is architecture-neutral.

If that's true, it's much more like C than like Java. (Which would explain why reflection is as limited as it is.)

That's why I think doing a JIT would be challenging in Joker (on top of Go) -- it'd have to either compile down to machine code (meaning, be different for each architecture), or to a pCode that'd (somehow) run faster in an interpreter written in Go than just running Joker code, or to a pCode for which custom interpreters would be written per architecture to squeeze more speed out of them.

Compiling down to a static executable (a la ClojureC), however, would be fairly straightforward (and I think ClojureC would be a great starting point), even though it might be limited in early implementations (might not support arbitrary `(eval ...)`-type code at all, nevermind actually compiling versus just interpreting it). All it'd need to do is generated Go code that implemented the Joker code, then compile that. (Joker already has `gen_data` and `generate-std.joke`, each of which does this for limited special cases.)

Now, there is a preliminary `plugin` package (supported on only Linux and MacOS), but using this would still mean compiling down to Go code, then shelling out to Go to build that as a plugin, then loading the resulting plugin to then execute the code -- hardly something a performant JIT would likely do.

But it might be interesting to write a Joker library that does all this (using a handwritten, or `gostd`-generated, wrapper around the `plugin` package), perhaps invoked via a `(compile ...)` function.

**Comment by candid82** [comment]
Thank you @dxlr8r and @jcburley for your input. Compiler topic aside, I think for now the entry point model will remain the same for Joker. I'll add a note about `(when (= *main-file* *file*)...` idiom to the readme.

As for the compiler, the only reason I am thinking about it is curiosity / self-education. There is absolutely no need for it to exist for the kind of use cases I have in mind for Joker. It can still be fun to work on one :) So I'll keep playing with the idea, but it seems more likely to materialize as a separate project (if at all).
