### ISSUE TITLE
File causes joker --lint to throw exception

### ISSUE THREAD

**Issue by martinklepsch** [candid82/joker#41]
When linting [boot/core.clj](https://github.com/boot-clj/boot/blob/260fe1d0e8e289d097187581a964ed7504700cb9/boot/core/src/boot/core.clj) joker throws an exception near the end of the file.

**Comment by candid82** [comment]
If you referring to this:

```
<stdin>:1316:21: Parse warning: duplicate require for boot.repl
Stacktrace:
  global <stdin>:1316:11
  joker.core/require <joker.core>:3339:3
  joker.core/apply <joker.core>:508:4
  joker.core/apply__ <joker.core>:3259:9
  joker.core/apply <joker.core>:508:4
  joker.core/apply__ <joker.core>:3216:20
  joker.core/ex-info <user>:195:27
```

this is expected behavior. It prints stacktrace because the problem was found while evaluating a macro. Stacktraces can be ignored in Joker output when running in linter mode. The important part is `<stdin>:1316:21: Parse warning: duplicate require for boot.repl`, which may (or may not) indicate an issue.

**Comment by martinklepsch** [comment]
Got it, seeing a stacktrace makes me think something isn't functioning as expected but I guess I'll close this then. :)

**Comment by candid82** [comment]
This is addressed by https://github.com/candid82/joker/commit/c29cc9819b73e19858ce25d45557f55104dc4794 to avoid confusion in the future.
