### ISSUE TITLE
go get would not build

### ISSUE THREAD

**Issue by rbucker** [candid82/joker#416]
not much to show except the trace

```
$ go get -u -v github.com/candid82/joker/...


github.com/candid82/joker (download)
github.com/candid82/liner (download)
github.com/mattn/go-runewidth (download)
get "go.etcd.io/bbolt": found meta tag get.metaImport{Prefix:"go.etcd.io/bbolt", VCS:"git", RepoRoot:"https://github.com/etcd-io/bbolt"} at //go.etcd.io/bbolt?go-get=1
go.etcd.io/bbolt (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/pkg/profile (download)
github.com/candid82/joker/core
github.com/candid82/joker/core/gen
# github.com/candid82/joker/core
../go/src/github.com/candid82/joker/core/array_map.go:73:9: undefined: TYPE
../go/src/github.com/candid82/joker/core/array_map.go:276:9: undefined: TYPE
../go/src/github.com/candid82/joker/core/buffer.go:34:9: undefined: TYPE
../go/src/github.com/candid82/joker/core/buffered_reader.go:35:9: undefined: TYPE
../go/src/github.com/candid82/joker/core/channel.go:36:9: undefined: TYPE
../go/src/github.com/candid82/joker/core/data.go:24:14: undefined: linter_allData
../go/src/github.com/candid82/joker/core/data.go:27:15: undefined: linter_jokerData
../go/src/github.com/candid82/joker/core/data.go:30:14: undefined: linter_cljxData
../go/src/github.com/candid82/joker/core/data.go:33:15: undefined: linter_cljData
../go/src/github.com/candid82/joker/core/data.go:35:15: undefined: linter_cljsData
../go/src/github.com/candid82/joker/core/data.go:35:15: too many errors
github.com/candid82/joker/core/gen_go
github.com/candid82/joker/tools/sum256dir
```

**Comment by jcburley** [comment]
Check the build instructions in the README.md file; Joker isn’t designed to build “out-of-the-box” via the go command, but provides a script (run.sh) that works on most Unix systems.

In particular, at least some of those errors indicate that the go generate step has not been performed, as Joker is built via initial steps that generate more Go code for a given build. core/object.go provides those initial steps in the first several lines of code.

**Comment by rbucker** [comment]
Well the doc did not say that my command did not work, just that this was the method.

```
go get -d github.com/candid82/joker
cd $GOPATH/src/github.com/candid82/joker
./run.sh --version && go install
```

BTW It's not uncommon for projects to pre-compute the intermediate files and preserve them in VCS presuming that are not machine dependent...  THANKS. Feel free to close if not worth working on.

**Comment by jcburley** [comment]
Joker would have difficulty with precomputed intermediate files being shipped (beyond the ones already done that way), because their contents can depend on the specific `GOOS` and `GOARCH` (i.e. the target OS and CPU architecture) used to build it.

E.g. see https://github.com/candid82/joker/issues/417.

Perhaps that could be worked around, but it'd be rather painful. Offhand I think it'd need to prebuild all OS/CPU combinations' generate files, then use build tags to ensure only the pertinent ones got pulled in for a specific build. That'd greatly increase the source distribution size of Joker (check the size of `core/a_code.go`, a generated file needed to build Joker but not currently in the distribution to get an idea), but that doesn't mean it's not worth considering.

See https://stackoverflow.com/questions/27402956/is-it-possible-use-go-build-with-extra-build-steps for some history on this, especially this comment:

> in go1.4 there will be the generate command. This will let you run arbitrary commands for pre-processing source files, but it always has to be a separate step that is run explicitly. You can't hook it into go get, go build, or go install.

>Many projects that require a more complicated build use a script or a Makefile, and eschew the general ability go get. Library packages however should strive to be get-able for simplicity in dependecy resolution.

It's also interesting to contemplate, if there was much demand for this, splitting Joker (cleanly) into a go-get-able library and a separate package that leverages that to build (using `go generate` and such) the standalone executable. I think the `gen_types` outputs might be suitable for directly inclusion in the library resulting from such a split; offhand, I can't recall any reason they'd be dependent on (and thus differ due to) a specific OS/CPU combination, whereas the `gen_code` output certainly is (at least when it comes to 32-bit versus 64-bit CPUs).

**Comment by candid82** [comment]
Readme instructions seem adequate to me. As long as they work I don't see an issue here.
