### ISSUE TITLE
Different color for duplicate require and obsolete require

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#49]
I tend to remove namespace requires that have squiggles in Emacs, but sometimes this is a duplicate require instead of an obsolete require. Then I will remove some refers that were needed, but should be combined in the single require.

Is it possible to get a different color in the squiggle for duplicate requires and unused requires?

**Comment by candid82** [comment]
Joker doesn't pick colors, it just reports errors and warnings. Both duplicate and unused require are warnings. However, it is possible to treat one of them as `info` instead of `warning` in flycheck. I am assuming you are using flycheck-joker for emacs integration. You can add `(info ...)` pattern to the [list of patterns](https://github.com/candid82/flycheck-joker/blob/master/flycheck-joker.el#L57) and match the message you want (i.e. `warning: unused namespace`). Flycheck will then use a different color for that particular message.
Can you provide an example (screenshot or actual code for `ns` form) to illustrate the issue? I am not sure I fully understand it.

**Comment by borkdude** [comment]
Yes, I use `flycheck-joker`. 

Full example:

```
(ns foo
  (:require [bar]
            [bar :refer [some-function]]
            [baz]))


(defn foo []
  (some-function 1))
```

I would like to have the curlies under `baz` to have a different color than the curlies under the second `bar`, so I know for sure I can remove it without even looking at the message.

I'll try your suggestion.

**Comment by candid82** [comment]
Gotcha. Let me know if my suggestion for flycheck-joker works out. We can potentially make it a configuration option I suppose.

**Comment by candid82** [comment]
Closing this as it's better addressed by flycheck-joker as discussed above. Feel free to open an issue (or, better yet, a PR!) against flycheck-joker.
