### ISSUE TITLE
"Unable to resolve symbol: deftest" when using `:refer :all`

### ISSUE THREAD

**Issue by jumarko** [candid82/joker#52]
I'm using flycheck-joker in spacemacs and I'm very happy with what it provides.
However, one thing that bothers me quite a lot is that joker reports `deftest` and `is` as unresolved symbols.
Here's the minimal repro for me:

```
(ns myapp.util-test
  (:require [myapp.util :as u]
                 [clojure.test :refer :all]))

(deftest namespaced-map
  (testing "keys are namespaced"
    (let [unqualified-keys {:name "Juraj" :age 32}
          qualified-keys #:user{:name "Juraj" :age 32}]
      (is (= qualified-keys unqualified-keys)))))
```

Here's the screenshot:
![image](https://user-images.githubusercontent.com/1083629/37591112-b6641762-2b6a-11e8-99eb-b2c6ceab2885.png)

I realized that this might be because `deftest` and `is` are macros so I tried to add following to ~/.joker (inspired by https://github.com/candid82/joker#reducing-false-positives):

```
{:known-macros [clojure.test/deftest clojure.test/testing clojure.test/is clojure.test/are]}
```
No success, however.

Any ideas why that happens?
Is it something that should work out of the box?

**Comment by candid82** [comment]
I need to document this in readme :). No, if you use `:refer :all` Joker won't be able to properly resolve symbols because it doesn't know what vars are declared in the required namespace (`clojure.test` in this case). There are generally two options here:
1. Refer specific symbols: `[clojure.test :refer [deftest testing is are]]`. There are not too many symbols in `clojure.test` namespace that are normally used, so this is not too tedious, and you only need to do it once per file. 
2. Use alias and qualified symbols: 
```
(:require [clojure.test :as t])
(t/deftest ...)
```
I generally prefer first option for `clojure.test` namespace.

There is now a third option (not released yet): https://github.com/candid82/joker/issues/50. It allows you to make Joker aware of any additional declarations (like `deftest` and `is`) by providing them in `.jokerd/linter.clj[s|c]` files. Note that such declarations become valid even if you don't `require` the namespace they come from, so this feature should be used sparingly (see discussion at https://github.com/candid82/joker/issues/50 for more details).

**Comment by jumarko** [comment]
Thanks for the clarification, very much appreciated.
I don't usually like to adjust my code just because of linter's business, however - and it's quite difficult when working on a large shared code base. Therefore, I'm looking forward to #50 being released :).

**Comment by tjbrandt** [comment]
I appreciate all the discussion here. For the most part, this works as expected. I put this in my .jokerd/linter.cljd:
```
(defn deftest [name & body])
(defn is ([form]) ([form msg]))
```

And I put this in my .joker:
```
{:ignored-unused-namespaces [clojure.test]}
```

The one caveat I'm trying to get around is the name of every test is now being shown as invalid, because joker is linting deftest as a function, which would expect the first argument (the test name in this case) to be a valid symbol. But joker can't find it because it's a _new_ symbol. Any thoughts?

Great work btw... new to the linter, but using it in vscode and loving it.

**Comment by candid82** [comment]
Try this:
```
(defmacro deftest [name & body] `(fn [] ~@body))
```

Pretty hacky, but should work. The linter will basically replace all your `deftest` forms with `(fn [] <body>)` at macro-expansion step and then lint the body as usual.

**Comment by tjbrandt** [comment]
Ha, awesome. That did work, and it makes sense. Thanks for the help!

**Comment by candid82** [comment]
Closing this issue for now as there is nothing actionable here at the moment. I have some ideas on how to make Joker aware of commonly used namespaces (like `clojure.test`), but nothing concrete yet. I'll put a note about `:refer :all` in readme for now.

**Comment by agzam** [comment]
@tjbrandt why not simply `(declare deftest)` in linter.clj ? I think that worked for me

**Comment by agzam** [comment]
@candid82 Can you suggest anything for things like
`(jdbc/with-db-transaction [t-conn *db*]`
where it complains that unable to resolve symbol `t-con`?

**Comment by candid82** [comment]
@agzam it should not complain if you have `clojure.java.jdbc/with-db-transaction` in `:known-macros` in `.joker` file.

**Comment by candid82** [comment]
@agzam Thanks for `(declare deftest)` suggestion. It also works and simpler than the solution I proposed above.

**Comment by didibus** [comment]
What I had to do was:

### In `.joker` add:
```
{:ignored-unused-namespaces [clojure.test]}
```

### In `.jokerd/linter.clj` add:
```
(in-ns 'joker.core)
(defmacro deftest [_ & body] `(fn [] ~@body))
(declare testing)
(declare is)
(declare are)
```

**Comment by tjbrandt** [comment]
@didibus Thanks for dropping in on this discussion even though it's been around for a while. The `defmacro` solution was working for several months, but for some reason this seemed to regress a few months ago and started showing linter errors again for `deftest`, `testing`, etc. (I'm using Spacemacs and was having issues even with the most recent v0.12.4.) I just lived with it until... your `in-ns` form fixed it!

If I do exactly what you suggest in `linter.clj`, for some reason it still gives me an error on the name of the `deftest`. (For example, `(deftest my-fn-test ...)` gives an error on `my-fn-test`, because without knowing `deftest` is a macro, I believe the linter looks for `my-fn-test` to be a valid symbol. This might be pretty specific to my setup though, who knows.)

But it now works for me after adding your `in-ns` to my `linter.clj`:

```
(in-ns 'joker.core)
(defmacro deftest [name & body] `(fn [] ~@body))
```

There might be a simpler way, but if I just use `declare` for `deftest` it was still giving me those errors. Hope this helps someone!

(@MicahElliott I know you were looking to a solution for this in the past too.)
