### ISSUE TITLE
Linter: warn on if with only one branch

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#9]
I'd like Joker linter to give a warning on the following:

``` 
(if true 1)
```
Often this happens when I mistakenly forget to handle the else case.

The warning could be: "if with only one branch, use when".

**Comment by candid82** [comment]
This is a grey area. Not everyone will agree this should be a warning. I do think it makes sense to implement this warning behind a config flag. However, it turned out to be trickier than I thought. The issue is that some built-in macros (most obviously, `when`) expand to `if` with no `else` branch:

```
user=> (macroexpand '(when 1 2))
(if 1 (do 2))
```

Since Joker (and Clojure) does macroexpansion before further analyzing (parsing in Joker's terminology) the forms, simple check in the parser (`if no else branch issue a warning`) would cause many false positives. 
I'll need to think about how to work around this issue. Any suggestions are appreciated.

**Comment by borkdude** [comment]
I understand the problem. It would be great if linter hints were configurable. Don't know a workaround for this problem, so I'll close it for now.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/27d039655ecf01e01d779e3429c4d6e6ab7a0e8c My "workaround" was changing `when` macro to expand to `if` with `else` branch. The warning is behind a config flag. To enable it, your .joker file should look like this:
```Clojure
{:known-macros [...]
 :rules {:if-without-else true}}
```

**Comment by borkdude** [comment]
Awesome!
